### ISSUE TITLE
Using &dark selector throws RangeError: Unsupported selector: &dark

### ISSUE THREAD

**Issue by jzillmann** [touchifyapp/svelte-codemirror-editor#12]
Having this
```
  <CodeMirror
    bind:value
    styles={{
      '&': {
        width: '80%',
        height: '18rem'
      },
      '&dark .cm-gutters': {
        backgroundColor: '#045'
      }
    }}
  />
```

throws following error:
```
index.js:5369 Uncaught RangeError: Unsupported selector: &dark
    at index.js:5369:27
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at finish (index.js:5365:40)
    at Array.map (<anonymous>)
    at render (style-mod.js:45:66)
    at new StyleModule (style-mod.js:50:28)
    at buildTheme (index.js:5363:12)
    at EditorView.theme (index.js:7078:56)
    at get_theme (CodeMirror.svelte:112:36)
```

Is that a problem with the library or something else ?

**Comment by SomaticIT** [comment]
Hello,
I think it's a configuration problem. I'm not sure that you can use the `&dark`.
This library only redirects styles to `codemirror`, it does not process them.
You can find some documentation here: https://codemirror.net/examples/styling
Thanks

**Comment by jzillmann** [comment]
You are right, have to use the baseTheme for that...
