### ISSUE TITLE
`Missing "./CodeMirror.svelte" specifier in "svelte-codemirror-editor" package` error on `npm run build`

### ISSUE THREAD

**Issue by dangerousNull** [touchifyapp/svelte-codemirror-editor#28]
Hi there,

I've run into an error with this Svelte library. When I try to build my project, I get an error saying that `./CodeMirror.svelte` is missing.

Here's the entire error log:

```
[commonjs--resolver] Missing "./CodeMirror.svelte" specifier in "svelte-codemirror-editor" package
error during build:
Error: Missing "./CodeMirror.svelte" specifier in "svelte-codemirror-editor" package
    at e (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:25)
    at n (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:627)
    at o (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21914:1297)
    at resolveExportsOrImports (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29466:20)
    at resolveDeepImport (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29485:31)
    at tryNodeResolve (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29210:20)
    at Object.resolveId (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:28978:28)
    at file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18670:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18570:28)
    at async resolveId (file:///home/ben/Documents/svelte-report-creator-v1/client/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17239:26)
```

Let me know if I didn't give enough information for this issue, and what I could do to help solve this issue.

### Development setup

- Svelte 4.2.8 (not using SvelteKit)
- Vite 5.0.8 (I did the exclusion for the optimization. Even tried the method in #27)

### Steps to duplicate

1. Run `npm install svelte-codemirror-editor`
2. Run `npm run build`

**Comment by KoljaL** [comment]
Same issue in my case :-(

**Comment by SomaticIT** [comment]
I can't replicate your issue.
Can you create a replication project on Github?
